### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by jwmatthys** [Qirky/FoxDot#114]
Hello! Latest commit 04e0b141d890e72624ee5acbd6d07e292a0de0de introduced a regression that causes all synth calls to fail. Tested on Linux and OSX.

```Welcome to FoxDot! Press Ctrl+H for help.
-----------------------------------------
>>> p1 >> blip()
Traceback (most recent call last):
  File "FoxDot/lib/TempoClock.py", line 373, in __run_block
    item.__call__()
  File "FoxDot/lib/TempoClock.py", line 752, in __call__
    self.obj.__call__(*self.args, **self.kwargs)
  File "FoxDot/lib/Players.py", line 653, in __call__
    self.send(verbose=(self.metro.solo == self and kwargs.get('verbose', True) and type(self.event['dur']) != rest))
  File "FoxDot/lib/Players.py", line 1473, in send
    for i in range(self.get_event_length(**kwargs)):
  File "FoxDot/lib/Players.py", line 1153, in get_event_length
    for attr, value in event.items():
AttributeError: 'NoneType' object has no attribute 'items'```

**Comment by jwmatthys** [comment]
Would this be a possible fix? FoxDot/lib/Players.py, lines 1149-50:

```        if kwargs:

            event.update(kwargs)
            event = event.copy()
```

**Comment by Qirky** [comment]
Ah thanks for the catch, not sure how I missed it. The fix is almost  right, just swap the order of the lines around and you got it. Fixed.
