### ISSUE TITLE
path problems with vrender

### ISSUE THREAD

**Issue by jwmatthys** [Qirky/FoxDot#119]
I think there's a problem with the tmp file paths for VRender:
```
Running voice renderization
[0, 2, 4, 5]
[1, 1.5, 0.5, 1.5]
[0, 2, 4, 5, 7, 9, 11]
[(60, 1, 100, 0), (64, 1.5, 100, 1), (67, 0.5, 100, 2.5), (69, 1.5, 100, 3.0)]
Composition:
[(60, 1, 100, 0), (64, 1.5, 100, 1), (67, 0.5, 100, 2.5), (69, 1.5, 100, 3.0)]
Traceback (most recent call last):
  File "FoxDot/lib/Code/main_lib.py", line 110, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "FoxDot/lib/Extensions/VRender/__init__.py", line 32, in __call__
    renderizeVoice(filename,lyrics,notes,durations,tempo,scale)
  File "FoxDot/lib/Extensions/VRender/VRender.py", line 14, in renderizeVoice
    compose(notes,durations,scale,LAST_MIDI,VOICE_XML_ORIGINAL)
  File "FoxDot/lib/Extensions/VRender/Composer.py", line 39, in compose
    createMidi(new_midi_path, composition)
  File "FoxDot/lib/Extensions/VRender/MidiFactory.py", line 19, in createMidi
    with open(midi_file, "wb") as output_file:
IOError: [Errno 2] No such file or directory: 'lib/Extensions/VRender/tmp/last_midi_generated_by_vrender.mid'
```

maybe the prefix needs to be FoxDot/lib/Extensions/VRender/tmp ?

**Comment by jwmatthys** [comment]
same for FoxDot/snd/_loop_
