### ISSUE TITLE
vrender throws Exception if tmp files don't exist

### ISSUE THREAD

**Issue by jwmatthys** [Qirky/FoxDot#120]
```
>>> vrender("v1", lyrics="hey ho lets go", notes=[0,2,4,5], dur=[1,1.5,0.5,1.5])
Running voice renderization
[0, 2, 4, 5]
[1, 1.5, 0.5, 1.5]
[0, 2, 4, 5, 7, 9, 11]
[(60, 1, 100, 0), (64, 1.5, 100, 1), (67, 0.5, 100, 2.5), (69, 1.5, 100, 3.0)]
Composition:
[(60, 1, 100, 0), (64, 1.5, 100, 1), (67, 0.5, 100, 2.5), (69, 1.5, 100, 3.0)]
Traceback (most recent call last):
  File "FoxDot/lib/Code/main_lib.py", line 110, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "FoxDot/lib/Extensions/VRender/__init__.py", line 32, in __call__
    renderizeVoice(filename,lyrics,notes,durations,tempo,scale)
  File "FoxDot/lib/Extensions/VRender/VRender.py", line 18, in renderizeVoice
    generateVoiceSpecification(lyrics,tempo,VOICE_XML_ORIGINAL,VOICE_XML_PROCESSED)
  File "FoxDot/lib/Extensions/VRender/VoiceSpecificator.py", line 6, in generateVoiceSpecification
    with open(inputMusicXMLPath, 'r') as c:
IOError: [Errno 2] No such file or directory: 'FoxDot/lib/Extensions/VRender/tmp/last_voice.musicxml'
```

Maybe change the flag to r+?

**Comment by jwmatthys** [comment]
Oops, nope, that doesn't fix it.

**Comment by Qirky** [comment]
Updated the `setup.py` file to include directories in extension modules so should work ok

**Comment by wblamkin** [comment]
Hi, I've encountered this problem as well, and don't really understand from the vrender documentation how to actually use this. I've double checked that VRender is in my Extensions folder, but beyond that I just keep getting this same error. Can anyone provide any help?

**Comment by Qirky** [comment]
What OS and version of Python are you using? Might be a permission issue as the file wouldn't exist if FoxDot doesn't have the  ability to create it in the  first place

**Comment by wblamkin** [comment]
I am running on macOS High Sierra, as for Python I have Python 3 installed but I believe it runs in Python 2.7? SuperCollider loads FoxDot from /Library/Python/2.7/site-packages/FoxDot/
I launch FoxDot from the Mac Terminal, and have to use the command "sudo FoxDot" to get permission to launch, so if there is a permission problem it could have something to do with that.

**Comment by Qirky** [comment]
I think it has something to do with the relative path of VRender so will look at making it an absolute path to avoid issues. Will update when this is done.

**Comment by mathigatti** [comment]
I changed them to be absolute paths about two months ago. Let me know if there is still some problem.

**Comment by RoboticMind** [comment]
I managed to partially solve this. Still having too many other issues with vrender to fully get it working.  I was having the same issue and saw that I was getting an error with musescore converting the files. I realized the latest relased version of it on the standard ubuntu apt repo is musescore 2 so I manually added in a ppa for musescore3 (https://launchpad.net/~mscore-ubuntu/+archive/ubuntu/mscore3-stable) and changed composer.py to use the command `musescore3` instead of `musescore`. This made the temp file exist and let it at least get that far. I also had to apply the patches in #224 to get a bit further. 

I keep getting issues with a few things 
1) the vrender syth definition keeps throwing errors in supercollider when importing vrender (it keeps saying `SynthDef vrender build failed ERROR: Pan2 input 0 is not audio rate:  0 scalar`) I tried figuring out how to change its synth def but could't figure out how 

2) the wav files do generate but for the weirdest reason it seems to not work no matter how long I set the dur for, yet the minute I shorten it with audacity it starts being able to play it. I've given up at figuring it out for now.

**Comment by mathigatti** [comment]
Hey, I'm sorry about it not working, I'm not updating this anymore but, in case it's useful for you, I keep this repositories updated https://github.com/mathigatti/midi2voice it's pretty much the same code, it converts midi files to singing voices.

I think vrender doesn't make sense as a synth, it should be just a function that we import and use inside FoxDot.

so maybe changing 

```
class VRenderSynthDef(SynthDef):

    def __init__(self):
        ...

    def __call__(self, ...):
        ...

vrender = VRenderSynthDef()
```
to something like this might fix the problems with supercollider.

```
def vrender(...):
        renderizeVoice(...)
```

[This](https://github.com/bu3nAmigue/FoxDot/blob/master/FoxDot/lib/Extensions/VRender/__init__.py) is the fork of foxdot I use, it has some hardcoded paths pointing out to [this](https://github.com/mathigatti/RealTimeSingingSynthesizer) project so it's not going to work in your computer but maybe it helps.

**Comment by mathigatti** [comment]
oh and about playing the audios, sinsy.jp adds 4 beats of silence at the beginning, you can try something like this, so you say you want to start on the fourth beat of the audio

v1 >> loop("v1",P[4:8])

**Comment by RoboticMind** [comment]
Ah that did fix both issues. Now it seems to work. Thank you!

**Comment by parisac** [comment]
@RoboticMind thanks for your post, got it working on Ubuntu 18.04 LTS with Python 3.x, aside from installing musicscore3 and changing reference to it in composer.py I merged in the [(branch](https://github.com/Qirky/FoxDot/pull/224) and it worked fine.
