### ISSUE TITLE
vrender http 404 error

### ISSUE THREAD

**Issue by jwmatthys** [Qirky/FoxDot#121]
Using this code:
```
from .Extensions.VRender import vrender
vrender("v1", lyrics="hey ho lets go", notes=[0,2,4,5], dur=[1,1.5,0.5,1.5])
```

```
>>> vrender("v1", lyrics="hey ho lets go", notes=[0,2,4,5], dur=[1,1.5,0.5,1.5])
Running voice renderization
[0, 2, 4, 5]
[1, 1.5, 0.5, 1.5]
[0, 2, 4, 5, 7, 9, 11]
[(60, 1, 100, 0), (64, 1.5, 100, 1), (67, 0.5, 100, 2.5), (69, 1.5, 100, 3.0)]Composition:
[(60, 1, 100, 0), (64, 1.5, 100, 1), (67, 0.5, 100, 2.5), (69, 1.5, 100, 3.0)]
Text:
['hey', 'ho', 'lets', 'go']
Traceback (most recent call last):
  File "FoxDot/lib/Code/main_lib.py", line 110, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "FoxDot/lib/Extensions/VRender/__init__.py", line 32, in __call__
    renderizeVoice(filename,lyrics,notes,durations,tempo,scale)
  File "FoxDot/lib/Extensions/VRender/VRender.py", line 22, in renderizeVoice
    download(urlfileName,LAST_VOICE_WAV)
  File "FoxDot/lib/Extensions/VRender/Sinsy.py", line 10, in download
    testfile.retrieve("http://sinsy.sp.nitech.ac.jp/temp/" + text + ".wav", wavPath)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 381, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 404, 'Not Found', <httplib.HTTPMessage instance at 0x7f8c8b0e5f38>)
```

Any ideas?

**Comment by jwmatthys** [comment]
OK, this actually seems to be caused because I didn't generate the musicXML correctly (because I didn't have musescore installed on the cmd line.) Resolved.
