### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by bwagner** [Qirky/FoxDot#13]
I get the error in the subject when running main.py.
I've seen other projects, where several python-versions lead to that problem.
I changed the shebang to:

`#!/usr/bin/env python
`
to no avail.

`/usr/bin/env python -V` gives:
`Python 2.7.12`

This is on OSX 10.11.6 (El Capitan)

Here's the trace:

```
FoxDot-master bwagner$ ./main.py
Traceback (most recent call last):
  File "./main.py", line 11, in <module>
    import FoxDot
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/__init__.py", line 9, in <module>
    from Code import *
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/Code/__init__.py", line 7, in <module>
    from ..Patterns.Operations import modi
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/Patterns/__init__.py", line 1, in <module>
    from Base import *
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/Patterns/Base.py", line 4, in <module>
    from ..Code.parse import brackets, closing_brackets
ImportError: No module named parse
```

**Comment by Qirky** [comment]
Line 4 in Patterns.Base can be deleted as I wrote a new parser but failed to remember to not import the old one. I have fixed this in the latest commit, as well as a few other changes, such as removing the automatic booting sclang on startup by default.

**Comment by bwagner** [comment]
Thank you.

Merely deleting the line 4 gives me this error:

```
0
Booting SuperCollider Server...
Traceback (most recent call last):
  File "./main.py", line 11, in <module>
    import FoxDot
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/__init__.py", line 13, in <module>
    from ServerManager import Server
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/ServerManager.py", line 146, in <module>
    Server = ServerManager()
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/ServerManager.py", line 28, in __init__
    self.boot()
  File "/Users/bwagner/Downloads/FoxDot-master/FoxDot/ServerManager.py", line 121, in boot
    self.daemon = Popen([SCLANG_EXEC, '-D', conf])
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

using the current version causes another error:

```
Warning: Error: SynthDef 'pads' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'varsaw' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'bass' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'crunch' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'scatter' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'bell' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'dub' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'scratch' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'pluck' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'creep' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'zap' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'fuzz' could not be added to the server:
while sending: [Errno 61] Connection refused
Warning: Error: SynthDef 'pulse' could not be added to the server:
while sending: [Errno 61] Connection refused
Traceback (most recent call last):
  File "./main.py", line 10, in <module>
    import FoxDot
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/__init__.py", line 42, in <module>
    BufferManager.load()
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/Buffers.py", line 47, in load
    self.server.bufferRead(buf, path("./Samples/" + fn))
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/ServerManager.py", line 80, in bufferRead
    self.client.send( message )
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/OSC.py", line 1222, in send
    raise OSCClientError("while sending: %s" % str(e))
FoxDot.OSC.OSCClientError: while sending: [Errno 61] Connection refused


```

Even starting SuperCollider manually, I get the error, albeit adding the SynthDefs seems to work:

```
Traceback (most recent call last):
  File "./main.py", line 10, in <module>
    import FoxDot
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/__init__.py", line 42, in <module>
    BufferManager.load()
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/Buffers.py", line 47, in load
    self.server.bufferRead(buf, path("./Samples/" + fn))
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/ServerManager.py", line 80, in bufferRead
    self.client.send( message )
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/OSC.py", line 1222, in send
    raise OSCClientError("while sending: %s" % str(e))
FoxDot.OSC.OSCClientError: while sending: [Errno 61] Connection refused
```

**Comment by Qirky** [comment]
Startup now requires you to open `FoxDot/SCLang/OSCFunc.scd` and execute that in SuperCollider and then start FoxDot. Can I check that you are doing that?

**Comment by bwagner** [comment]
This got me a little further. I managed to execute the first few examples from http://foxdot.org/index.php/start/
However, it chokes on the line` john >> pluck()` as below. I tried the same with `j >> pluck()` which worked. However, as soon as I execute `j.stop()`, `j` becomes unusable (i.e. nothing is audible) and I have to pick a different variable to get an audible effect. I can only use 1- or 2-letter variable names. Everything else results in the error below. (Once I use `Cmd-.`, the variables no longer audible due to `stop()` start working again)

```
Traceback (most recent call last):
  File "/Users/bwagner/projects/3rdparty/FoxDot/FoxDot/Code/__init__.py", line 68, in __call__
    exec code in self.namespace
  File "FoxDot", line 2, in <module>
NameError: name 'john' is not defined

```

**Comment by Qirky** [comment]
The documentation is pretty poor at the moment and hopefully I'll have time to clear it up a bit. I will update it proper as soon as I have a few hours free - thanks for pointing it out. So... At startup, FoxDot automatically assigns 'empty' Player Objects to any 1 or 2 character variable. Player Objects are what are updated using the `>>` syntax and a SynthDef. If you want to use a variable name that is longer than 2 characters, you just need to define it: `foo = PlayerObject()` and then `foo >> pads()` etc will work. I need to remove the Beatles references from the old startup guide and also explain this and some config stuff too. Hope this helps!
