### ISSUE TITLE
After installing 7.13 FoxDot does not launch.

### ISSUE THREAD

**Issue by WiggyWire** [Qirky/FoxDot#146]
So I downloaded 7.13 from github, now it does not launch. I get the following error.

```
dan@wiggy:~$ python -m FoxDot
IOError: Unable to update 'slideFrom' effect.
IOError: Unable to update 'pitchBend' effect.
IOError: Unable to update 'coarse' effect.
IOError: Unable to update 'striate' effect.
IOError: Unable to update 'highPassFilter' effect.
IOError: Unable to update 'filterSwell' effect.
IOError: Unable to update 'bandPassFilter' effect.
IOError: Unable to update 'combDelay' effect.
IOError: Unable to update 'spinPan' effect.
IOError: Unable to update 'reverb' effect.
Warning: Unable to update 'loop' SynthDef.
Warning: Unable to update 'gsynth' SynthDef.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/FoxDot-0.7.13-py2.7.egg/FoxDot/__init__.py", line 21, in <module>
    from .lib import *
  File "/usr/local/lib/python2.7/dist-packages/FoxDot-0.7.13-py2.7.egg/FoxDot/lib/__init__.py", line 12, in <module>
    from .TempoClock import *
  File "/usr/local/lib/python2.7/dist-packages/FoxDot-0.7.13-py2.7.egg/FoxDot/lib/TempoClock.py", line 53, in <module>
    from .Players import Player
  File "/usr/local/lib/python2.7/dist-packages/FoxDot-0.7.13-py2.7.egg/FoxDot/lib/Players.py", line 141, in <module>
    from .Key import *
  File "/usr/local/lib/python2.7/dist-packages/FoxDot-0.7.13-py2.7.egg/FoxDot/lib/Key.py", line 4, in <module>
    from .TimeVar import TimeVar
  File "/usr/local/lib/python2.7/dist-packages/FoxDot-0.7.13-py2.7.egg/FoxDot/lib/TimeVar.py", line 731
    def __init__(self, func, *args, pattern=None):
                                          ^
SyntaxError: invalid syntax

```

Your SuperCollider version:3.7.0
Your operating system and version: Linux 4.16.12-rt5-avl1 x86_64
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian

I can't install the later version of supercollider as it has dependency that are not supported in my current version of linux. It depends when the package maintainers can fix that.

**Comment by Qirky** [comment]
Thanks for catching this - it wasn't properly tested for Python 2 and should be working ok now

**Comment by WiggyWire** [comment]
Thanks for the quick turn around - much appreciated. I updated FoxDot and reinstalled. Works fine. I can use Python3 if it helps in future.

**Comment by Qirky** [comment]
No that's fine - I want to make sure FoxDot is compatible with both version of Python
