### ISSUE TITLE
Multiple find path errors when executing main.py in windows

### ISSUE THREAD

**Issue by lrs** [Qirky/FoxDot#15]
- OS: Microsoft Windows Version 10.0.14393
- FoxDot version: v0.1.9

### Description

"The system cannot find the path specified: 'D:\\Apps\\FoxDot\\Samples\\...".
I tried adding the missing folder each time I received the error a few times:
```
D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 74, in __init__
    for f in sorted(os.listdir(lower)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\c\\lower/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 84, in __init__
    for f in sorted(os.listdir(upper)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\g\\upper/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 84, in __init__
    for f in sorted(os.listdir(upper)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\k\\upper/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 74, in __init__
    for f in sorted(os.listdir(lower)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\l\\lower/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 84, in __init__
    for f in sorted(os.listdir(upper)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\m\\upper/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 84, in __init__
    for f in sorted(os.listdir(upper)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\n\\upper/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 84, in __init__
    for f in sorted(os.listdir(upper)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\r\\upper/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 74, in __init__
    for f in sorted(os.listdir(lower)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\u\\lower/*.*'

D:\Apps\FoxDot>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import FoxDot
  File "D:\Apps\FoxDot\FoxDot\__init__.py", line 19, in <module>
    from TempoClock import *
  File "D:\Apps\FoxDot\FoxDot\TempoClock.py", line 10, in <module>
    from Players import Player, PlayerKey
  File "D:\Apps\FoxDot\FoxDot\Players.py", line 27, in <module>
    BufferManager = Buffers.BufferManager()
  File "D:\Apps\FoxDot\FoxDot\Buffers.py", line 98, in __init__
    for f in sorted(os.listdir(folder)):
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Apps\\FoxDot\\FoxDot\\Samples\\_\\ampersand/*.*'

D:\Apps\FoxDot>
```

**Comment by Qirky** [comment]
Thanks for letting me know. It was caused because empty directories weren't added to the repo. Just surrounded this with a try and except for now and it should work. Releasing a major update over the weekend with an updated readme etc. `main.py` is now `__main__.py` but it's basically the same now. Let me know if this can be closed.

**Comment by lrs** [comment]
Thanks. The FoxDot IDE now runs. Please close this issue.
