### ISSUE TITLE
How to connect to remote server

### ISSUE THREAD

**Issue by hyansuper** [Qirky/FoxDot#152]
In the file FoxDot/lib/Settings/conf.txt, first line is 'ADDRESS='localhost'' , what does it mean? can I set ADDRESS=[IP of remote server running supercollider] ?
I have tried that but got an 'invalid  argument ' error

**Comment by Qirky** [comment]
That is what is meant to happen but quite a few users have had issues with this feature. It is either an OSC issue or a network issue but not sure at the moment

**Comment by hyansuper** [comment]
Thanks for your fast reply. What I don't understand is the error is not "connection refused " or something ，but "invalid argument "

**Comment by hyansuper** [comment]
I use python3.6
`python3 -m FoxDot`  produce the error:
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/OSC3.py", line 1170, in connect
    self._ensureConnected(address)
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/OSC3.py", line 1079, in _ensureConnected
    self.socket.connect(address)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/__init__.py", line 21, in <module>
    from .lib import *
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/__init__.py", line 12, in <module>
    from .TempoClock import *
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/TempoClock.py", line 53, in <module>
    from .Players import Player
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/Players.py", line 136, in <module>
    from .SCLang.SynthDef import SynthDefProxy, SynthDef, SynthDefs
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/SCLang/__init__.py", line 4, in <module>
    from .SynthDef import SynthDefs, SynthDef, SynthDefProxy, SampleSynthDef, CompiledSynthDef
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/SCLang/SynthDef.py", line 6, in <module>
    from ..ServerManager import DefaultServer
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/ServerManager.py", line 1060, in <module>
    DefaultServer = SCLangServerManager(ADDRESS, PORT, PORT2)
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/ServerManager.py", line 213, in __init__
    self.sclang.connect( (self.addr, self.SCLang_port) )
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/ServerManager.py", line 81, in connect
    self.client.connect(addr)
  File "/usr/local/lib/python3.6/dist-packages/FoxDot/lib/OSC3.py", line 1174, in connect
    raise OSCClientError("SocketError: %s" % str(e))
FoxDot.lib.OSC3.OSCClientError: SocketError: [Errno 22] Invalid argument

`

**Comment by hyansuper** [comment]
On the remote server, I just type FoxDot.start in SuperCollider without additional settings, I not sure if SuperCollider has any options to allow non-local connections
