### ISSUE TITLE
Pvar error msgs

### ISSUE THREAD

**Issue by qantuum** [Qirky/FoxDot#163]
Hi ! 

I just want to adress some strange bug that triggers when I manipulate a player including Pvars.

Let's take this example : 
```
fg >> sitar(Pvar([P[1,P*(2,3),P+(1,2,3,7,8),2],P[1,0],P[2,7,10,var([4,7,10],8)]],4),sus=Pvar([P[1,1,0.25,1],1,1],4),drive=0.02,vib=1,vibdepth=0.02,dur=PDur(3,16))
```

Well, when I tried to add the dur or the drive items while playing, or when I do a Clock.clear(), so to say, any alteration I want to bring to my player while playing, I triggered this error msg : 
When I left and started over FoxDot with the line entirely typed, the bug did not not trigger, it was only on update.

```
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\FoxDot\lib\Code\main_lib.py", line 116, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 1, in <module>
    from __future__ import absolute_import, division, print_function
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\FoxDot\lib\TempoClock.py", line 663, in clear
    player.kill()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\FoxDot\lib\Players.py", line 1735, in kill
    self.reset()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\FoxDot\lib\Players.py", line 610, in reset
    self.degree  = " " if self.synthdef is SamplePlayer else 0
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\FoxDot\lib\Players.py", line 486, in __setattr__
    self.__dict__[name].update_pattern()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\FoxDot\lib\Key.py", line 648, in update_pattern
    self.pattern[:] = asStream(self.parent.attr[self.key])
TypeError: 'Pvar' object does not support item assignment
```

I mean, this is like Chinese to me and I do not understand what I'm doing wrong... 
Can you kindly either investigate in this or tell me what I'm doing wrong ?

Thanks a lot...

**Comment by Qirky** [comment]
I can't seem to reproduce the error - are you able to get the error consistently? If so, can you give me the code you run before and after you get the error? Thanks

**Comment by qantuum** [comment]
Hey,

took me some time to get the error again.

Below execution code : 

`
sc >> blip(PTri(5) + sb.degree, dur=Pvar([PDur(7,10),P[1/2,1/4]]))
`

To be a bit more accurate, here is also the chronology of events : 
1/ run code block in song context
2/ Clock.clear(), stopping it all
3/ error message triggers
4/ trying to execute code again
5/ error message triggers

**Comment by Qirky** [comment]
I wasn't able to get the error using the code you supplied but I've worked it out. It's caused if another player references a player attribute (e.g. `p1.dur`) that uses a Pvar. So this code should cause the error:

```
