### ISSUE TITLE
Install UniCodeError

### ISSUE THREAD

**Issue by bmbouter** [Qirky/FoxDot#165]
On a Debian VM (an official image) I do a basic FoxDot install. After installing pip3 and supercollider ustin `apt` I install:

```
vagrant@stretch:~$ pip3 install FoxDot
Collecting FoxDot
  Downloading https://files.pythonhosted.org/packages/90/d7/e187a36e569852e1cb4290200b11d660700eb3d424591b31f409302f6949/FoxDot-0.7.19.tar.gz (37.5MB)
    100% |################################| 37.5MB 43kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kclgbup4/FoxDot/setup.py", line 6, in <module>
        long_description=f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4831: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kclgbup4/FoxDot/

```

When cloning from source I get the same error:

```
vagrant@stretch:~/FoxDot$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    long_description=f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4754: ordinal not in range(128)
```

There is some non ascii character in the README.md. Replacing `long_description=f.read()` with `long_description=''` allows me to install it.

**Comment by Qirky** [comment]
Hey thanks! Turns out it was non-ascii apostrophe that somehow got in there. Removed it now.

**Comment by bmbouter** [comment]
Thank you! I wasn't able to get it running unfortunately on the Debian machine I was testing on. Supercollider was saying `Could not allocate new area. Supercollider failed to start`. I should probably email their usergroup or forum.

**Comment by lueo** [comment]
Hi I met the same problem. However it could to be resolved by reading the README.md with UTF-8 encoding.
My OS language is a Traditional Chinese (cp950) one.

* Modifications (in setup.py):
```
with open("README.md", "r", encoding='utf-8') as f:
    long_description=f.read()
```


* Error messages:
```
(env) C:\Users\leonardh\Project\FoxDot>python setup.py install
Traceback (most recent call last):
  File "C:\Users\leonardh\Project\FoxDot\setup.py", line 6, in <module>
    long_description=f.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 3819: illegal multibyte sequence

```
