### ISSUE TITLE
Tutorials showing special character (â€™) instead of ‘ (apostrophe) character

### ISSUE THREAD

**Issue by jeremy886** [Qirky/FoxDot#169]
I just started trying FoxDot again during holidays and I noticed this problem I didn't see before.

> Special character (â€™) is used instead of ‘ (apostrophe) character in tutorials

I sampled two tutorials and found another character (â€˜): [See here](https://repl.it/@jeremy886/unicodechecker)

```
Python 3.6.1 (default, Dec 2015, 13:05:11)
[GCC 4.8.2] on linux
04_using_patterns.py
b'\xe2\x80\x99' ’
b'\xe2\x80\x99' ’
b'\xe2\x80\x98' ‘
b'\xe2\x80\x99' ’
b'\xe2\x80\x99' ’
01_intro.py
b'\xe2\x80\x98' ‘
b'\xe2\x80\x99' ’
b'\xe2\x80\x99' ’
right character is b
```

**Comment by jeremy886** [comment]
I think this is a problem for Windows. After seeing the error message when loading Tutorial 10:

```
    Warning: Could not fetch info from SCLang server. Using defaults...
    Exception in Tkinter callback
    Traceback (most recent call last):
      File "C:\Users\jerem\scoop\apps\python\3.7.3\lib\tkinter\__init__.py", line 1705, in __call__
        return self.func(*args)
      File "C:\Users\jerem\.virtualenvs\foxdot\lib\site-packages\FoxDot\lib\Workspace\Editor.py", line 700, in loadfile
        self.set_all(f.read())
      File "C:\Users\jerem\scoop\apps\python\3.7.3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 93: character maps to <undefined>
```

I was able to fix both issues by adding encoding to Editor.py but I suspect more file open issues may exist. However, it's okay for me now.

Quick Fix: https://github.com/jeremy886/FoxDot/commit/5b41a5a9d25fcb9e058426d3a908b5d8038f101c

**Comment by Qirky** [comment]
I believe this is fixed, can you confirm on your systems?

**Comment by aguillon** [comment]
I don't have Windows and I can't confirm that it is fixed. However, this issue is due to the use of single and double quotation marks in the tutorials (most of the times instead of apostrophe '). I suggest to remove those special characters.
