### ISSUE TITLE
AttributeError: 'ChildTimeVar' object has no attribute 'encode'

### ISSUE THREAD

**Issue by CrashServer** [Qirky/FoxDot#171]
Hi, when I play this : `y4 >> blip(sus=y4.dur*linvar([0.5,1.2],[24,0]), chop=4)` , 
I've got this error, only when referencing to other/same player + linvar + chop 

`Traceback (most recent call last):
  File "C:\Users\sebas\FoxDot\FoxDot\lib\TempoClock.py", line 563, in __run_block
    item.__call__()
  File "C:\Users\sebas\FoxDot\FoxDot\lib\TempoClock.py", line 957, in __call__
    self.obj.__call__(*self.args, **self.kwargs)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Players.py", line 670, in __call__
    self.send(verbose=(self.metro.solo == self and kwargs.get('verbose', True)))
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Players.py", line 1514, in send
    self.send_osc_message(self.event, i, timestamp=timestamp, verbose=verbose, **kwargs)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Players.py", line 1574, in send_osc_message
    self.push_osc_to_server(packet, timestamp, verbose, **kwargs)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Players.py", line 1596, in push_osc_to_server
    compiled_msg = self.metro.server.get_bundle(synthdef, message, timestamp = timestamp + delay)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\ServerManager.py", line 568, in get_bundle
    pkg, this_node = self.get_post_env_effect_nodes(this_node, this_bus, group_id, packet)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\ServerManager.py", line 479, in get_post_env_effect_nodes
    msg.append( osc_packet )
  File "C:\Users\sebas\FoxDot\FoxDot\lib\OSC3.py", line 295, in append
    self.append(arg, typehint)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\OSC3.py", line 306, in append
    tag, binary = OSCArgument(argument, typehint)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\OSC3.py", line 757, in OSCArgument
    binary  = OSCString(next)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\OSC3.py", line 723, in OSCString
    next = bytes(next.encode("UTF-8"))
AttributeError: 'ChildTimeVar' object has no attribute 'encode'`

**Comment by Qirky** [comment]
Forced FoxDot to send float values to the server, so this should be fixed
