### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'PGroup'

### ISSUE THREAD

**Issue by reolcor** [Qirky/FoxDot#190]
Examples from Tutorial 03: Playing Samples:

`d1 >> play("x[--]xu[--]x", sample=(d1.degree=="x"))`

or 

`d1 >> play("x[--]xu[--]x", sample=(d1.degree=="x")*2)`

or 

`d1 >> play("x[--]xu[--]x", sample=(d1.degree=="x")*2 + (d1.degree=="-")*5)`

Output:

```
Traceback (most recent call last):
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/TempoClock.py", line 568, in __run_block
    output = item.__call__()
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/TempoClock.py", line 970, in __call__
    value = self.obj.__call__(*self.args, **self.kwargs)
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Players.py", line 664, in __call__
    self.get_event()
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Players.py", line 1525, in get_event
    self.event = dict(map(lambda attr: (attr, self.now(attr)), self.attr.keys()))
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Players.py", line 1525, in <lambda>
    self.event = dict(map(lambda attr: (attr, self.now(attr)), self.attr.keys()))
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Players.py", line 1436, in now
    attr_value = self.unpack(attr_value)
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Players.py", line 1390, in unpack
    item = self.update_player_key_relation(item)
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Players.py", line 1367, in update_player_key_relation
    return item.now()
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Key.py", line 365, in now
    value = self.value.now() if hasattr(self.value, "now") else self.value
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Key.py", line 365, in now
    value = self.value.now() if hasattr(self.value, "now") else self.value
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Key.py", line 367, in now
    return self.calculate(value)
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Key.py", line 306, in new_func
    return func(item)
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Key.py", line 165, in <lambda>
    function = lambda value: int(value == other)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'PGroup'
```

Foxdot v0.7.38

**Comment by Qirky** [comment]
Ah, thanks. Fixed.
