### ISSUE TITLE
Bar character (|) not working with play()

### ISSUE THREAD

**Issue by jwmatthys** [Qirky/FoxDot#196]
There is a directory of samples for bar and it shows up in print(Samples), but using the bar symbol with play leads to an error: (Ubuntu Studio 19.04; US keyboard)

```
>>> p1 >> play("|")
Traceback (most recent call last):
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Code/main_lib.py", line 155, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Players.py", line 379, in __rshift__
    self.update(other.name, other.degree, **other.kwargs)
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Players.py", line 834, in update
    setattr(self, "degree", degree if degree != "" else " ")
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Players.py", line 460, in __setattr__
    value = asStream(value)
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Patterns/Main.py", line 1487, in asStream
    return data if isinstance(data, Pattern) else Pattern(data)
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Patterns/Main.py", line 97, in __init__
    self.fromString(data)
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Patterns/Parse.py", line 263, in fromString
    self.data = ParsePlayString(string)
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Patterns/Parse.py", line 29, in ParsePlayString
    output, _ = feed(string)
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Patterns/Parse.py", line 126, in feed
    j = string.next_char_index("|", start=i+1)
  File "/home/jwmatthys/.local/lib/python3.6/site-packages/FoxDot/lib/Patterns/PlayString.py", line 52, in next_char_index
    return self.string[start:].index(char) + start
ValueError: '|' is not in list
```

**Comment by Qirky** [comment]
Ahh yes, the characters "|", ">", and "<" no longer map to samples but to syntax for organising the play string. However, they weren't removed from the list of names - so I've done that now.
