### ISSUE TITLE
AttributeError: RandomPlayGroup instance has no attribute 'divide'

### ISSUE THREAD

**Issue by lvm** [Qirky/FoxDot#20]
This *pattern* syntax will throw an exception 

```python
dr >> play("[x.{o_~}.x]")
```
I'll just leave the pattern  (`[x{.~}]`)  because i'm not being able to copy the log from the console.

**Comment by lvm** [comment]
from the python interpreter managed to get the traceback, hope it's useful

```python
>>> dr >> play("[x.{o_~}.x]")
Traceback (most recent call last):
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Code/main_lib.py", line 84, in __call__
    exec self._compile(code) in self.namespace
  File "FoxDot", line 1, in <module>
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 244, in __rshift__
    self.update(other.name, other.degree, **other.kwargs)
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 486, in update
    setattr(self, "degree", degree)
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 257, in __setattr__
    value = asStream(value) if not isinstance(value, (PlayerKey, TimeVar.var)) else value
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Patterns/Base.py", line 549, in asStream
    return Pattern(data)
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Patterns/Base.py", line 22, in __init__
    self.fromString(data)
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Patterns/Base.py", line 170, in fromString
    self.data = Parse(string)
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Patterns/Parse.py", line 18, in __call__
    output, _ = self.parse(string)
  File "FoxDot/.env/lib/python2.7/site-packages/FoxDot/lib/Patterns/Parse.py", line 99, in parse
    char.divide(len(chars))
AttributeError: RandomPlayGroup instance has no attribute 'divide'
```

**Comment by Qirky** [comment]
This has now been fixed in the last commit
