### ISSUE TITLE
[Linux] PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages/FoxDot/lib/Settings/conf.txt'

### ISSUE THREAD

**Issue by funcrab** [Qirky/FoxDot#248]
Hello. Thanks for the fun tools.

# Environment
- Arch Linux (Manjaro-sway)
- Kernel: 5.10.18-zen-1-zen-lts510-g513e3c94a40f
- python 3.9.7-1
- tk 8.6.11.1-1
- supercollider 3.12.1-1

# Reproduction Procedure
1. start `FoxDot` in console
2. open the menu `Help & Settings` -> `Open config file (advanced)`
3. press `Save Changes`
-> conf.txt cannot be saved.

## The following error occurs in the console
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/lib/python3.9/site-packages/FoxDot/lib/Workspace/ConfigFile.py", line 74, in save_changes
    f = open(self.filepath, "w") # writing a file
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages/FoxDot/lib/Settings/conf.txt'
```

**Comment by Qirky** [comment]
Does `sudo` work at all? I think that might be a temporary workaround, other than editing the config file itself manually, but there might be some better way to manage local storage for these files tbh

**Comment by funcrab** [comment]
When I run the following, I can save the configuration file
- `sudo FoxDot`

I dealt with this by changing the permissions of the corresponding file in the following way.
- `chmod 666 /usr/lib/python3.9/site-packages/FoxDot/lib/Settings/conf.txt`

I don't think this is a high priority issue, but it would be better if the configuration files were created for each user in the following location to avoid sharing them across the machine
- `$XDG_CONFIG_HOME/foxdot/conf.txt`
