### ISSUE TITLE
dependency on tkinter?

### ISSUE THREAD

**Issue by shakfu** [Qirky/FoxDot#252]
I was looking forward to running foxdot on a headless rpi with supercollider via ssh when I saw that tkinter of all things is a dependency:

```bash
$ python3 -m FoxDot
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/FoxDot/__main__.py", line 82, in <module>
    from .lib.Workspace.Editor import workspace
  File "/home/pi/.local/lib/python3.7/site-packages/FoxDot/lib/Workspace/Editor.py", line 18, in <module>
    from .tkimport import *
  File "/home/pi/.local/lib/python3.7/site-packages/FoxDot/lib/Workspace/tkimport.py", line 4, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'
```
Can this be disabled?

**Comment by Qirky** [comment]
If you want to run FoxDot with the default GUI then, no, it can't be disabled as the interface is built using Tkinter (see [README](https://github.com/Qirky/FoxDot#installation-and-startup)). You can import FoxDot as standalone Python library into your own projects/use it in other editors such as [Atom](https://foxdot.org/installation/#using-atom) or [Emacs](https://foxdot.org/installation/#using-emacs)
