### ISSUE TITLE
FoxDot does not support Python 3.11

### ISSUE THREAD

**Issue by astrojuanlu** [Qirky/FoxDot#256]
```
$ python -m FoxDot
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/__init__.py", line 106, in <module>
    from .lib import *
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/__init__.py", line 12, in <module>
    from .TempoClock import *
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/TempoClock.py", line 53, in <module>
    from .Players import Player
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/Players.py", line 141, in <module>
    from .Key import *
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/Key.py", line 3, in <module>
    from .Patterns import *
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/Patterns/__init__.py", line 72, in <module>
    from .Main       import *
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/Patterns/Main.py", line 81, in <module>
    class metaPattern(object):
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/Patterns/Main.py", line 632, in metaPattern
    @loop_pattern_method
     ^^^^^^^^^^^^^^^^^^^
  File "/home/juanlu/Projects/Other/foxdot-live-coding-workshop/.venv/lib/python3.11/site-packages/FoxDot/lib/Patterns/Main.py", line 61, in loop_pattern_method
    new_function.argspec = inspect.getargspec(f)
                           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

I know that this project is not actively maintained anymore (gh-255), but putting this here for the record.

**Comment by TheNuSan** [comment]
I have the same issue, I managed to get something running by replacing in the source code every "getargspec" by "getfullargspec" and replacing "keywords" by "varkw" in lib\TempoClock.py
but I don't know if that fixes everything

**Comment by TonyIvanova** [comment]
> I have the same issue, I managed to get something running by replacing in the source code every "getargspec" by "getfullargspec" and replacing "keywords" by "varkw" in lib\TempoClock.py but I don't know if that fixes everything

Had to make changes in Main.py as well, and now it opens without errors, but doesn't produce sound..

**Comment by TonyIvanova** [comment]
> I have the same issue, I managed to get something running by replacing in the source code every "getargspec" by "getfullargspec" and replacing "keywords" by "varkw" in lib\TempoClock.py but I don't know if that fixes everything

It is running without errors now, but doesn't produce sound.

**Comment by TheNuSan** [comment]
> > I have the same issue, I managed to get something running by replacing in the source code every "getargspec" by "getfullargspec" and replacing "keywords" by "varkw" in lib\TempoClock.py but I don't know if that fixes everything
> 
> It is running without errors now, but doesn't produce sound.

I made a fix in my fork if you want to check, I have proper sound and everything seems to work:
[https://github.com/TheNuSan/FoxDot](https://github.com/TheNuSan/FoxDot)
if it doesn't work, maybe check all the other steps (launching supercollider before, starting foxdot plugin in supercollider ...)

**Comment by felipebastos** [comment]
> I have the same issue, I managed to get something running by replacing in the source code every "getargspec" by "getfullargspec" and replacing "keywords" by "varkw" in lib\TempoClock.py but I don't know if that fixes everything

Fixing getargspec for getfullargspec will be needed on Repeat module too.

My tests are running under:
- Windows 11:
- Python 3.11
- Poetry
- SuperCollider 3.13.0-RC1
- FoxDot from PyPI 0.8.12
- No Jack nor ASIO driver for now
- Presonus Studio 26C and its official drivers

No special config was needed on this except for the code fix.

**Comment by henriquesebastiao** [comment]
I have the same problems when trying to run it with python 3.12.3, however it works perfectly with python 3.10.

**Comment by astrojuanlu** [comment]
FoxDot 0.9.0 supports Python 3.11, 3.12, 3.13, and 3.14 ❤️ closing!

**Comment by astrojuanlu** [comment]
xref #273
