### ISSUE TITLE
Running FoxDot on OSX 13.31

### ISSUE THREAD

**Issue by lasconcore** [Qirky/FoxDot#264]
Hello,

Thanks in advance for your help :)

I am getting the bellow response in terminal whilst trying to launch FoxDot. Any guidance as to what I've got wrong?

laurenceconway@MacBook-Air FoxDot % python3 -m FoxDot
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/laurenceconway/FoxDot/FoxDot/__init__.py", line 106, in <module>
    from .lib import *
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/__init__.py", line 12, in <module>
    from .TempoClock import *
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/TempoClock.py", line 53, in <module>
    from .Players import Player
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/Players.py", line 141, in <module>
    from .Key import *
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/Key.py", line 3, in <module>
    from .Patterns import *
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/Patterns/__init__.py", line 72, in <module>
    from .Main       import *
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/Patterns/Main.py", line 81, in <module>
    class metaPattern(object):
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/Patterns/Main.py", line 632, in metaPattern
    @loop_pattern_method
     ^^^^^^^^^^^^^^^^^^^
  File "/Users/laurenceconway/FoxDot/FoxDot/lib/Patterns/Main.py", line 61, in loop_pattern_method
    new_function.argspec = inspect.getargspec(f)
                           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
laurenceconway@MacBook-Air FoxDot %

**Comment by gorhgorh** [comment]
this is not an osx issue this is a pyton issue, use python 3.10.X as getargs was removed in 3.11
