### ISSUE TITLE
TclError: bad event type or keysym "."

### ISSUE THREAD

**Issue by Scinawa** [Qirky/FoxDot#4]
LinuxMusic% python main.py 
>>> from FoxDot import *
>>> Clock.start()
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    a = interface()
  File "main.py", line 29, in __init__
    App.__init__(self, "FoxDot - Live Coding with Python and SuperCollider")
  File "/home/user/FoxDot/FoxDot-master/FoxDot/Interface/__init__.py", line 86, in __init__
    self.text.bind("<Control-.>",       self.killall)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1092, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1047, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: bad event type or keysym "."

After this, the software does not close, but hang still.
My version of python is 2.7.9.

**Comment by Qirky** [comment]
Hi Scinawa, is there anything in particular happening leading up to this? Are you printing anything to the console? I will be adding a new commit shortly, so please do feel free to download and try replicated the error if you could. Thanks.

**Comment by Qirky** [comment]
Hi Scinawa, what operating system are you using?
