### ISSUE TITLE
Problem on start

### ISSUE THREAD

**Issue by Metaxi** [Qirky/FoxDot#49]
I cooked SuperCollider. it start to listen:
`server already running
Listening for messages from FoxDot
FoxDot`
Then i type 

> sudo python -m FoxDot

 and errors come:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/FoxDot/__init__.py", line 12, in <module>
    from .lib import *
  File "/usr/local/lib/python2.7/dist-packages/FoxDot/lib/__init__.py", line 27, in <module>
    from .Workspace import get_keywords
  File "/usr/local/lib/python2.7/dist-packages/FoxDot/lib/Workspace/__init__.py", line 3, in <module>
    from .Editor import *
  File "/usr/local/lib/python2.7/dist-packages/FoxDot/lib/Workspace/Editor.py", line 25, in <module>
    from tkinter import *
ImportError: No module named tkinter
`

System is Linux Mint 18.2
SuperCollider version is 3.6.6

**Comment by Qirky** [comment]
Seems you are using Python 2.7. Could you test if you have `Tkinter` installed (with a capital "T"  in Python 2.7). It looks like it fails to import that version and then tries to import `tkinter` (with a lower case "T") assuming it's Python 3. Could you run python and then try the following code:

```
import Tkinter 
import ttk
import tkFont
import tkFileDialog
import tkMessageBox
```

**Comment by Metaxi** [comment]
Thank you for quick answer. It is solved. What i did:
1. apt-get install python-tk
2. start python and import libraries you wrote.
3. sudo python -m FoxDot

Foxdot started!

**Comment by Qirky** [comment]
Great, I'll add the solution to the FAQ
