### ISSUE TITLE
Foxdot 0.4.10 does not launch

### ISSUE THREAD

**Issue by Almenon** [Qirky/FoxDot#50]
After installing the latest version of Foxdot with pip on windows 10 with python 3.5.0 I get the following:

> C:\WINDOWS\system32>python -m FoxDot
C:\Program Files\Python 3.5\python.exe: Error while finding spec for 'FoxDot.\_\_main\_\_' (<class 'AttributeError'>: module 'sys' has no attribute 'maxint'); 'FoxDot' is a package and cannot be directly executed

> C:\WINDOWS\system32>python -m FoxDot.\_\_main\_\_
C:\Program Files\Python 3.5\python.exe: Error while finding spec for 'FoxDot.\_\_main\_\_' (<class 'AttributeError'>: module 'sys' has no attribute 'maxint')

> C:\WINDOWS\system32>python -c "import FoxDot; module.main()"
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\__init__.py", line 12, in <module>
    from .lib import *
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\lib\__init__.py", line 24, in <module>
    from .TempoClock import *
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\lib\TempoClock.py", line 53, in <module>
    from .Players import Player
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\lib\Players.py", line 158, in <module>
    from .Key import *
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\lib\Key.py", line 3, in <module>
    from .Patterns import *
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\lib\Patterns\__init__.py", line 72, in <module>
    from .Main       import *
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\lib\Patterns\Main.py", line 862, in <module>
    class GeneratorPattern(random.Random):
  File "C:\Program Files\Python 3.5\lib\site-packages\FoxDot\lib\Patterns\Main.py", line 867, in GeneratorPattern
    MAX_SIZE = sys.maxint
AttributeError: module 'sys' has no attribute 'maxint'
```

Foxdot 0.4.9 works, so it looks like this bug was introduced with v10.

**Comment by Qirky** [comment]
Thanks for catching this, should be fixed now
