### ISSUE TITLE
play('{-}') gives NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by Chovin** [Qirky/FoxDot#54]
```py
>>> p1 >> play('{xo}')
Traceback (most recent call last):
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Code/main_lib.py", line 106, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 1, in <module>
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Players.py", line 352, in __rshift__
    self.update(other.name, other.degree, **other.kwargs)
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Players.py", line 777, in update
    setattr(self, "degree", degree if len(degree) > 0 else " ")
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Players.py", line 436, in __setattr__
    for item in value:
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Patterns/Main.py", line 223, in __iter__
    yield self.getitem(i)
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Patterns/Main.py", line 199, in getitem
    val = val.getitem(j)
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Patterns/Main.py", line 905, in getitem
    value = self.func(index)
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Patterns/Generators.py", line 65, in func
    value = self.choose()
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Patterns/Generators.py", line 60, in choose
    return self.data[self.choice(range(self.MAX_SIZE))]
NameError: name 'xrange' is not defined
```

**Comment by Qirky** [comment]
This is fixed in the most recent commit
