### ISSUE TITLE
FoxDot doesn't start after most recent commit

### ISSUE THREAD

**Issue by Chovin** [Qirky/FoxDot#69]
```py
$ python3 -m FoxDot
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/__init__.py", line 12, in <module>
    from .lib import *
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/__init__.py", line 24, in <module>
    from .TempoClock import *
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/TempoClock.py", line 53, in <module>
    from .Players import Player
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Players.py", line 153, in <module>
    from .SCLang.SynthDef import SynthDefProxy, SynthDef, SynthDefs
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/SCLang/__init__.py", line 4, in <module>
    from .SynthDef import SynthDefs, SynthDef, SynthDefProxy, SampleSynthDef, CompiledSynthDef
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/SCLang/SynthDef.py", line 6, in <module>
    from ..ServerManager import DefaultServer
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/ServerManager.py", line 5, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'
```

doing something like `from .TempoClock import Queue` gives me a circular dependency

**Comment by Qirky** [comment]
Sorry! I forgot to push my last commit which fixes the error. The new ServerManager stuff (getting information from SuperCollider) only worked with Python 2 and I've updated it. Should work fine now.
