### ISSUE TITLE
permissions errors for standard users in mac

### ISSUE THREAD

**Issue by moabbott** [Qirky/FoxDot#74]
All appears to go well with installation.  However when I run "python -m FoxDot" in Terminal I get the following permission error:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/Library/Python/2.7/site-packages/FoxDot/__init__.py", line 12, in <module>
    from .lib import *
  File "/Library/Python/2.7/site-packages/FoxDot/lib/__init__.py", line 24, in <module>
    from .TempoClock import *
  File "/Library/Python/2.7/site-packages/FoxDot/lib/TempoClock.py", line 53, in <module>
    from .Players import Player
  File "/Library/Python/2.7/site-packages/FoxDot/lib/Players.py", line 154, in <module>
    from .Effects import FxList
  File "/Library/Python/2.7/site-packages/FoxDot/lib/Effects.py", line 221, in <module>
    fx.save()
  File "/Library/Python/2.7/site-packages/FoxDot/lib/Effects.py", line 125, in save
    with open(self.filename, 'w') as f:
I**OError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/FoxDot/osc/sceffects/vibrato.scd**'

This is executing as a standard user.  When I run it as an admin user and use sudo, it works.  However I am trying to install this in on several machines in a lab environment where users will not have sudo ability.  Am I doing something wrong?  Is there any way around this so that standard users can use FoxDot?

**Comment by Qirky** [comment]
By default FoxDot writes the .scd files at startup but this is rather wasteful and will throw permission errors if not run with sudo. In the last commit it now only writes to file if the source code has changed or if the file doesn't exist so should be ok now!
