### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#78]
Hi, I'm getting this in the Terminal at start-up, any suggestions?

while sending: [Errno 61] Connection refused

By the way, when I installed FoxDot and opened it, it worked a treat, no problem.

Thanks in advance - Joe

**Comment by Qirky** [comment]
Hi Joe, what OS are you using? Another user found that installing "jack2" fixed this error for them but I haven't got much more info than that.

**Comment by joesh1** [comment]
Hi Ryan, I just upgraded to High Sierra so I'm on OS 10.13.2. I'm not getting anything at all, very strange indeed, especially as the day before yesterday I installed it and tried it out no problem. However, today, no sound and the same error message appearing in the post window. As an example for a test I tried to run pluck and got this: 

>>> p1 >> pluck()
while sending: [Errno 61] Connection refused
while sending: [Errno 61] Connection refused
while sending: [Errno 61] Connection refused
while sending: [Errno 61] Connection refused
while sending: [Errno 61] Connection refused 

By the way, I'm a SuperCollider user, so I ran everything as suggested and it seemed ok. I'll have another check, one never knows something might not of worked properly.

**Comment by joesh1** [comment]
By the way Ryan, I see that FoxDot has automatically used python 2.7, although I also have 3.6 installed. Could there be something here?

**Comment by Chovin** [comment]
you can start it with python 3.6 by doing `python3 -m FoxDot`

**Comment by joesh1** [comment]
I tried that out of interest, but since FoxDot stores/sets itself up in python 2.7, it just gives an error message saying no such program (as FoxDot) exists. I might try installing FD in python 3 later to see what happens.

**Comment by Qirky** [comment]
You'll have to install using Python3 using `pip3 install FoxDot` or `python3 setup.py install` if you have the files from here. FoxDot should work fine for both Python 2 and 3 though so I don't think that's the problem. Have you installed "jack2"?

**Comment by joesh1** [comment]
Yes, I've installed "jack2" (I assume Jack Audio), but nothing has changed. 

Out of interest, if I pass via Python 3 I get a different error message: 
'ConnectionRefusedError' object is not subscriptable

I wonder if I should just disinstall Python2/3 and start all over again. What's strange is that there seems - I suspect - a problem between SuperCollider and FoxDot. I've checked the quarks and everything is correct, but the fact that I don't seem to get any sound/connection when typing a simple command (ex: p1 >> pluck()), which also produces the error messages seems odd?

**Comment by joesh1** [comment]
Ah, just got a traceback (not sure why), which might be of interest:

`^CTraceback (most recent call last):
  File "//anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "//anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "//anaconda/lib/python2.7/site-packages/FoxDot/__init__.py", line 12, in <module>
    from .lib import *
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/__init__.py", line 149, in <module>
    instantiate_player_objects()
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/__init__.py", line 130, in instantiate_player_objects
    FoxDotCode.namespace[arg] = Player(arg)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 326, in __init__
    self.reset()
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 526, in reset
    setattr(self, key, value)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 443, in __setattr__
    value = asStream(value)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Patterns/Main.py", line 1209, in asStream
    return data if isinstance(data, Pattern) else Pattern(data)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Patterns/Main.py", line 107, in __init__
    self.make()
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Patterns/Main.py", line 863, in make
    elif type(data) is str and len(data) > 1:
KeyboardInterrupt`

**Comment by joesh1** [comment]
^CTraceback (most recent call last):
  File "//anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "//anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "//anaconda/lib/python2.7/site-packages/FoxDot/__init__.py", line 12, in <module>
    from .lib import *
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/__init__.py", line 149, in <module>
    instantiate_player_objects()
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/__init__.py", line 130, in instantiate_player_objects
    FoxDotCode.namespace[arg] = Player(arg)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 326, in __init__
    self.reset()
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 526, in reset
    setattr(self, key, value)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 443, in __setattr__
    value = asStream(value)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Patterns/Main.py", line 1209, in asStream
    return data if isinstance(data, Pattern) else Pattern(data)
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Patterns/Main.py", line 107, in __init__
    self.make()
  File "//anaconda/lib/python2.7/site-packages/FoxDot/lib/Patterns/Main.py", line 863, in make
    elif type(data) is str and len(data) > 1:
KeyboardInterrupt

**Comment by Qirky** [comment]
The traceback looks like it was caused by pressing Ctrl+C during startup? Googling the issue it seems that it's [a Mac only issue](https://stackoverflow.com/questions/42962772/python-socket-connection-refused-on-mac-but-not-on-windows) and might be to do with a recent two-way communication added with SuperCollider. I'll have to add a test for MacOS and only use the single direction communication with SuperCollider, which shouldn't take too long but I won't have time until later today at the earliest

**Comment by joesh1** [comment]
That would be great as I'm hoping to convince my faculty (at school) to let me teach FoxDot as a course later this school year!

**Comment by Qirky** [comment]
Could you update using `pip install FoxDot --upgrade` then open the FoxDot editor, go to Help & Settings -> Open config file (advanced) and then change the line `GET_SC_INFO=True` to `GET_SC_INFO=False`. If you restart FoxDot are you able to avoid the error?

**Comment by joesh1** [comment]
Hi, just tried that suggestion, sorry no luck still getting the same error. 

By the way, I ran Brew doctor earlier for something else and noticed this:

_Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs._

Is that of any help?

**Comment by Qirky** [comment]
Hmm, will the problem seems to be the connection between FoxDot (which starts fine) and SuperCollider via the OSCServer/OSCClient. When you run `FoxDot.start` in SuperCollider, it should say "booting 57110" - is that correct or is it a different number?

**Comment by joesh1** [comment]
Whoops, you've just hit the nail-on-the-head, or should I say I should hit myself on the head! I hadn't thought to start FoxDot in SC. I must have gone through the process automatically the first time (by following the download/setup instructions), but since then didn't think about that. I'm really sorry to have waisted your time, but also thanks, as the problem, or should I say mystery, is solved.
