### ISSUE TITLE
"Exception in Tkinter callback" after trying GUI menu options

### ISSUE THREAD

**Issue by CadaverLab** [Qirky/FoxDot#87]
I cloned FoxDot from git (just now), and it installed just fine. When i run it from command line and try the option "Toggle Transparency" i get this on the terminal:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "/home/deadguy/bin/FoxDot/FoxDot/lib/Workspace/Editor.py", line 673, in toggle_transparency
    self.text.config(background=alpha)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1479, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1470, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown color name "systemTransparent"
```

If i try "Open config file" i get 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/deadguy/bin/FoxDot/FoxDot/lib/Workspace/ConfigFile.py", line 26, in __init__
    self.root.iconbitmap(FOXDOT_ICON)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1865, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/deadguy/bin/FoxDot/FoxDot/lib/Workspace/img/icon.gif" not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "/home/deadguy/bin/FoxDot/FoxDot/lib/Workspace/Editor.py", line 616, in open_config_file
    Config(FOXDOT_CONFIG_FILE).start()
  File "/home/deadguy/bin/FoxDot/FoxDot/lib/Workspace/ConfigFile.py", line 31, in __init__
    self.root.tk.call('wm', 'iconphoto', self.root._w, PhotoImage(file=FOXDOT_ICON))
_tkinter.TclError: can't use "pyimage2" as iconphoto: not a photo image
```

Lastly, if i try "Toggle Menu" it doesn't spit out any error, but i can't toggle it back. It just shows up as a thin line i can't seem to interact with.

this happens both on python 2 and 3 on (Manjaro) Linux.

**Comment by Qirky** [comment]
Ah I think these are Linux issues. Best I can do is catch the errors and print something to the console I'm afraid!

**Comment by CadaverLab** [comment]
Well, that's a shame.
Is there a way to set these options manually? or at the very least edit the config file?

**Comment by Qirky** [comment]
If you're working from the GitHub repo you can pull the latest commits and see if that fixes the issue with the config file. I don't think transparency will work with your O/S though

**Comment by CadaverLab** [comment]
I just pulled latest and can now see the config dialog correctly.
Toggle transparency and re-toggling the menu still don't work, but they don't spit out a bunch of python errors to the terminal now. Instead it's a much cleaner message in the foxdot console.

Too bad about the transparency, but at least i can edit config now :+1:

**Comment by oboingo** [comment]
I use linux, but not a compositing WM, so I don't see transparency anyway.  Not sure what the intended effect is supposed to look like, but this works on a default Ubuntu 17.10.  I just hacked at it really quickly, it isn't really tested, plus I really don't know what it is supposed to look like.

But I think the important part is the alpha command.  Maybe that points everyone in the right direction?

```
def toggle_transparency(self, event=None):
        """ Sets the text and console background to black and then removes all black pixels from the GUI """
        setting_transparent = self.transparent.get()
        try:
            if setting_transparent:
                if SYSTEM == WINDOWS:
                    alpha = "#000001" if SYSTEM == WINDOWS else "systemTransparent"
                    self.text.config(background=alpha)
                    self.linenumbers.config(background=alpha)
                    self.console.config(background=alpha)
                    self.root.wm_attributes('-transparentcolor', alpha)
                else:
                    self.root.wm_attributes("-alpha", 0.3)
            else:
                self.text.config(background=colour_map['background'])
                self.linenumbers.config(background=colour_map['background'])
                self.console.config(background="Black")
                if SYSTEM == WINDOWS:
                    self.root.wm_attributes('-transparentcolor', "")
                else:
                    self.root.wm_attributes("-alpha", 1)
        except TclError as e:
            print(e)
        return```

**Comment by CadaverLab** [comment]
I can confirm that @oboingo 's code works on my end.
